#!/bin/sh
###############################################################################
if [[ $(acdcli upload /home/metalgeek/.local-encrypt/* /) = *upload complete* ]]; then
  rm -rf /home/metalgeek/.local-encrypt/*
  fi
