#!/bin/sh
###############################################################################
if [[ $(acdcli upload /home/metalgeek/.local-encrypt/* /) = *100.0%* ]]; then
  rm -rf /home/metalgeek/.local-decrypt/*
  fi
